# Generated by Django 2.2.5 on 2019-12-11 17:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2030)])),
                ('genre', models.CharField(max_length=60)),
                ('director', models.CharField(max_length=60)),
                ('plot', models.CharField(max_length=600)),
                ('runtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('film', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='db.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500)),
                ('add_date', models.DateField(auto_now=True)),
                ('related_to', models.IntegerField(blank=True, default=None)),
                ('film', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='db.Film')),
            ],
        ),
    ]
