# Generated by Django 2.2.5 on 2019-12-12 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Film'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Film'),
        ),
    ]
