# Generated by Django 2.2.5 on 2019-12-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20191223_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='db.Film'),
        ),
    ]
