# Generated by Django 2.2.5 on 2019-12-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20191212_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['add_date']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-year']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
