# Generated by Django 2.2.5 on 2019-12-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20191228_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Comment'),
        ),
    ]
